image: maven:3-jdk-8

stages:
    - build
    - deploy

maven-build:
    stage: build
    script: "mvn package"
    artifacts:
      paths:
        - target/surefire-reports/TEST-*.xml
      reports:
        junit:
          - target/surefire-reports/TEST-*.xml

maven-deploy:
    stage: deploy
    script:
      - "mvn package" 
      - echo "Produção ok"